In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

# Crypto Data (CoinGecko API)

In [ ]:
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=4&sparkline=False"
#by change the page number from 1 to 4 and save the each 200 response in each data
response = requests.get(url)
data4 = response.json()

In [ ]:
len(data4)

250

In [ ]:
len(data3)

250

In [ ]:
len(data2)

250

In [ ]:
data1

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 6159686,
  'market_cap': 123075012357220,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 123075012357220,
  'total_volume': 5567724492422,
  'high_24h': 6398258,
  'low_24h': 5992958,
  'price_change_24h': 103537,
  'price_change_percentage_24h': 1.70962,
  'market_cap_change_24h': 1861326031510,
  'market_cap_change_percentage_24h': 1.53557,
  'circulating_supply': 19997225.0,
  'total_supply': 19997225.0,
  'max_supply': 21000000.0,
  'ath': 11187013,
  'ath_change_percentage': -44.93896,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 3993.42,
  'atl_change_percentage': 154145.91358,
  'atl_date': '2013-07-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:23.011Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 180568,
  'market_cap': 21777974517664,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 21777974517664,
  'total_volume': 2464047766066,
  'high_24h': 189793,
  'low_24h': 176345,
  'price_change_24h': 2191.37,
  'price_change_percentage_24h': 1.2285,
  'market_cap_change_24h': 236138402201,
  'market_cap_change_percentage_24h': 1.09619,
  'circulating_supply': 120692182.1241322,
  'total_supply': 120692182.1241322,
  'max_supply': None,
  'ath': 431946,
  'ath_change_percentage': -58.19647,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 28.13,
  'atl_change_percentage': 641778.96064,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 38.16454803315929,
   'currency': 'btc',
   'percentage': 3816.454803315929},
  'last_updated': '2026-03-03T10:51:24.416Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 92.06,
  'market_cap': 16915222486246,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 17418803134421,
  'total_volume': 9283527675114,
  'high_24h': 92.11,
  'low_24h': 91.48,
  'price_change_24h': 0.582543,
  'price_change_percentage_24h': 0.63681,
  'market_cap_change_24h': 117138331617,
  'market_cap_change_percentage_24h': 0.69733,
  'circulating_supply': 183633868264.8259,
  'total_supply': 189100805662.9562,
  'max_supply': None,
  'ath': 105.52,
  'ath_change_percentage': -12.73498,
  'ath_date': '2025-01-25T16:51:57.989Z',
  'atl': 36.86,
  'atl_change_percentage': 149.81543,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:21.858Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 57653,
  'market_cap': 7858730865466,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 7858730154854,
  'total_volume': 136455188959,
  'high_24h': 59636,
  'low_24h': 56633,
  'price_change_24h': 941.64,
  'price_change_percentage_24h': 1.66042,
  'market_cap_change_24h': 129167333753,
  'market_cap_change_percentage_24h': 1.67108,
  'circulating_supply': 136358651.3299999,
  'total_supply': 136358639.0,
  'max_supply': 200000000.0,
  'ath': 121422,
  'ath_change_percentage': -52.51871,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 2.58,
  'atl_change_percentage': 2230406.20483,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:22.816Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 124.09,
  'market_cap': 7573622364075,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 12395634756471,
  'total_volume': 333855215608,
  'high_24h': 129.62,
  'low_24h': 122.75,
  'price_change_24h': 0.341794,
  'price_change_percentage_24h': 0.27619,
  'market_cap_change_24h': 12068801948,
  'market_cap_change_percentage_24h': 0.15961,
  'circulating_supply': 61090376977.0,
  'total_supply': 99985708785.0,
  'max_supply': 100000000000.0,
  'ath': 313.99,
  'ath_change_percentage': -60.47796,
  'ath_date': '2025-07-21T15:02:00.541Z',
  'atl': 0.159343,
  'atl_change_percentage': 77778.63681,
  'atl_date': '2013-08-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:19.082Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 92.06,
  'market_cap': 7000370024740,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 7001257849047,
  'total_volume': 632800890838,
  'high_24h': 92.12,
  'low_24h': 91.48,
  'price_change_24h': 0.586944,
  'price_change_percentage_24h': 0.64163,
  'market_cap_change_24h': 127130958766,
  'market_cap_change_percentage_24h': 1.84965,
  'circulating_supply': 76038515589.59924,
  'total_supply': 76048159200.17885,
  'max_supply': None,
  'ath': 1327.87,
  'ath_change_percentage': -93.06272,
  'ath_date': '2025-01-23T04:45:51.184Z',
  'atl': 65.31,
  'atl_change_percentage': 41.05218,
  'atl_date': '2021-05-19T13:14:05.611Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:21.519Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 7759.25,
  'market_cap': 4420308645419,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 4821375514461,
  'total_volume': 542165713199,
  'high_24h': 8214.17,
  'low_24h': 7610.11,
  'price_change_24h': 90.63,
  'price_change_percentage_24h': 1.1818,
  'market_cap_change_24h': 49505545914,
  'market_cap_change_percentage_24h': 1.13264,
  'circulating_supply': 569767706.1961758,
  'total_supply': 621464311.1927567,
  'max_supply': None,
  'ath': 25396,
  'ath_change_percentage': -69.44733,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 38.03,
  'atl_change_percentage': 20305.28555,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:19.660Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 25.88,
  'market_cap': 2453055551058,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 2453055315631,
  'total_volume': 39865769148,
  'high_24h': 26.0,
  'low_24h': 25.73,
  'price_change_24h': 0.132913,
  'price_change_percentage_24h': 0.51616,
  'market_cap_change_24h': 13890896216,
  'market_cap_change_percentage_24h': 0.56949,
  'circulating_supply': 94741894752.6196,
  'total_supply': 94741885659.9852,
  'max_supply': None,
  'ath': 36.53,
  'ath_change_percentage': -29.13605,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.117589,
  'atl_change_percentage': 21911.6895,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 146.95820660413548,
   'currency': 'usd',
   'percentage': 14695.820660413547},
  'last_updated': '2026-03-03T10:51:20.879Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 94.75,
  'market_cap': 1464364189204,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 1464364189204,
  'total_volume': 1124838600,
  'high_24h': 94.83,
  'low_24h': 94.18,
  'price_change_24h': 0.569116,
  'price_change_percentage_24h': 0.60427,
  'market_cap_change_24h': 8634524971,
  'market_cap_change_percentage_24h': 0.59314,
  'circulating_supply': 15454657905.817,
  'total_supply': 15454657905.817,
  'max_supply': None,
  'ath': 120.96,
  'ath_change_percentage': -21.66861,
  'ath_date': '2025-10-28T06:00:43.161Z',
  'atl': 13.78,
  'atl_change_percentage': 587.36489,
  'atl_date': '2025-10-31T14:57:19.271Z',
  'roi': None,
  'last_updated': '2026-03-03T06:21:50.357Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 8.26,
  'market_cap': 1395680293193,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 1395877407060,
  'total_volume': 135834798802,
  'high_24h': 8.9,
  'low_24h': 8.23,
  'price_change_24h': -0.1352369038648913,
  'price_change_percentage_24h': -1.6101,
  'market_cap_change_24h': -23324828964.642334,
  'market_cap_change_percentage_24h': -1.64375,
  'circulating_supply': 168942613126.579,
  'total_supply': 168966473126.579,
  'max_supply': None,
  'ath': 53.62,
  'ath_change_percentage': -84.5871,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 0.00552883,
  'atl_change_percentage': 149371.74315,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:13.541Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 4476.42,
  'market_cap': 951284649918,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1425713730530,
  'total_volume': 6318064975,
  'high_24h': 4659.16,
  'low_24h': 4408.6,
  'price_change_24h': 21.32,
  'price_change_percentage_24h': 0.47866,
  'market_cap_change_24h': -1454091231.067505,
  'market_cap_change_percentage_24h': -0.15262,
  'circulating_supply': 213544699.0,
  'total_supply': 320044699.0,
  'max_supply': 400000000.0,
  'ath': 5758.63,
  'ath_change_percentage': -22.64963,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 245.71,
  'atl_change_percentage': 1712.85494,
  'atl_date': '2022-09-21T23:38:03.675Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:21.368Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 92.07,
  'market_cap': 906481536523,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 906481536523,
  'total_volume': 1997388024,
  'high_24h': 92.11,
  'low_24h': 91.47,
  'price_change_24h': 0.58149,
  'price_change_percentage_24h': 0.63562,
  'market_cap_change_24h': -22280302523.06653,
  'market_cap_change_percentage_24h': -2.39893,
  'circulating_supply': 9840437468.014477,
  'total_supply': 9840437468.014477,
  'max_supply': None,
  'ath': 92.23,
  'ath_change_percentage': -0.12723,
  'ath_date': '2026-01-29T16:30:24.390Z',
  'atl': 79.67,
  'atl_change_percentage': 15.61706,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:20.915Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 24.4,
  'market_cap': 897962751533,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 1097454876915,
  'total_volume': 60490706563,
  'high_24h': 26.37,
  'low_24h': 24.31,
  'price_change_24h': -0.46038307467218686,
  'price_change_percentage_24h': -1.85211,
  'market_cap_change_24h': -17365983049.4281,
  'market_cap_change_percentage_24h': -1.89724,
  'circulating_supply': 36820032120.64621,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 225.26,
  'ath_change_percentage': -89.16956,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 1.38,
  'atl_change_percentage': 1673.78265,
  'atl_date': '2017-11-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:12.642Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 40423,
  'market_cap': 808385773080,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 808394234956,
  'total_volume': 31166896304,
  'high_24h': 41342,
  'low_24h': 39944,
  'price_change_24h': 224.98,
  'price_change_percentage_24h': 0.55967,
  'market_cap_change_24h': 5071494793,
  'market_cap_change_percentage_24h': 0.63132,
  'circulating_supply': 20002156.14665078,
  'total_supply': 20002365.52165078,
  'max_supply': 21000000.0,
  'ath': 242198,
  'ath_change_percentage': -83.30994,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 5536.54,
  'atl_change_percentage': 630.11272,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:24.001Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 836.97,
  'market_cap': 771026106481,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 824597161432,
  'total_volume': 170080632,
  'high_24h': 841.06,
  'low_24h': 817.32,
  'price_change_24h': 1.89,
  'price_change_percentage_24h': 0.22595,
  'market_cap_change_24h': 1715933738,
  'market_cap_change_percentage_24h': 0.22305,
  'circulating_supply': 921232104.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 888.26,
  'ath_change_percentage': -5.72672,
  'ath_date': '2025-12-01T06:16:28.002Z',
  'atl': 56.97,
  'atl_change_percentage': 1369.78598,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:15.760Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 2937.53,
  'market_cap': 700513540449,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 2827716062152,
  'total_volume': 34678125962,
  'high_24h': 3076.33,
  'low_24h': 2772.26,
  'price_change_24h': 165.27,
  'price_change_percentage_24h': 5.96147,
  'market_cap_change_24h': 39612092526,
  'market_cap_change_percentage_24h': 5.99365,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 5213.52,
  'ath_change_percentage': -43.6556,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 321.88,
  'atl_change_percentage': 812.61803,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:14.924Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 31606,
  'market_cap': 582517336437,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 582517336437,
  'total_volume': 8717088563,
  'high_24h': 32129,
  'low_24h': 30844,
  'price_change_24h': -87.66336299495742,
  'price_change_percentage_24h': -0.2766,
  'market_cap_change_24h': -1665843034.6610107,
  'market_cap_change_percentage_24h': -0.28516,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 72026,
  'ath_change_percentage': -56.11857,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 13.57,
  'atl_change_percentage': 232795.69303,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:16.747Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 796.93,
  'market_cap': 564025834502,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 796534187315,
  'total_volume': 39541161571,
  'high_24h': 842.11,
  'low_24h': 788.68,
  'price_change_24h': 2.33,
  'price_change_percentage_24h': 0.29365,
  'market_cap_change_24h': 1594335599,
  'market_cap_change_percentage_24h': 0.28347,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 3862.15,
  'ath_change_percentage': -79.36571,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 9.55,
  'atl_change_percentage': 8247.70901,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:12.768Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 92.03,
  'market_cap': 552602774717,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 552602774717,
  'total_volume': 16008589687,
  'high_24h': 92.1,
  'low_24h': 91.41,
  'price_change_24h': 0.611884,
  'price_change_percentage_24h': 0.66929,
  'market_cap_change_24h': 2608996762,
  'market_cap_change_percentage_24h': 0.47437,
  'circulating_supply': 5998141404.817833,
  'total_supply': 5998141404.817833,
  'max_supply': None,
  'ath': 92.91,
  'ath_change_percentage': -0.89007,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 78.05,
  'atl_change_percentage': 17.99097,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:13.793Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 14.5,
  'market_cap': 549852705907,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 549852705907,
  'total_volume': 1240312459,
  'high_24h': 14.95,
  'low_24h': 14.5,
  'price_change_24h': -0.17460500326239448,
  'price_change_percentage_24h': -1.19021,
  'market_cap_change_24h': -9132164949.464233,
  'market_cap_change_percentage_24h': -1.63371,
  'circulating_supply': 37930228206.58018,
  'total_supply': 37930228206.58018,
  'max_supply': None,
  'ath': 17.72,
  'ath_change_percentage': -18.18796,
  'ath_date': '2026-01-31T16:41:41.560Z',
  'atl': 5.31,
  'atl_change_percentage': 173.12364,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:24.163Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 13.82,
  'market_cap': 455552311628,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 690851382192,
  'total_volume': 11351544499,
  'high_24h': 14.81,
  'low_24h': 13.77,
  'price_change_24h': -0.23891239764366112,
  'price_change_percentage_24h': -1.6993,
  'market_cap_change_24h': -7775271353.003479,
  'market_cap_change_percentage_24h': -1.67814,
  'circulating_supply': 32971533657.67472,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 58.01,
  'ath_change_percentage': -76.22726,
  'ath_date': '2021-05-16T09:48:45.220Z',
  'atl': 0.02966141,
  'atl_change_percentage': 46391.00705,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:19.949Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 92.03,
  'market_cap': 428795262021,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 428795262021,
  'total_volume': 251099213087,
  'high_24h': 92.08,
  'low_24h': 91.42,
  'price_change_24h': 0.58668,
  'price_change_percentage_24h': 0.64159,
  'market_cap_change_24h': 335721460,
  'market_cap_change_percentage_24h': 0.07836,
  'circulating_supply': 4656762552.261821,
  'total_supply': 4656762552.261821,
  'max_supply': None,
  'ath': 92.17,
  'ath_change_percentage': -0.13318,
  'ath_date': '2026-01-28T15:56:38.616Z',
  'atl': 83.75,
  'atl_change_percentage': 9.90532,
  'atl_date': '2025-05-02T03:46:49.689Z',
  'roi': None,
  'last_updated': '2026-03-03T10:51:21.265Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 0.843399,
  'market_cap': 403556528862,
  'market_cap_rank': 23,
  'fully_diluted_valuation': 970811133821,
  'total_volume': 2810878416,
  'high_24h': 0.86365,
  'low_24h': 0.831864,
  'price_change_24h': 0.00277406,
  'price_change_percentage_24h': 0.33,

In [ ]:
# convert the data into dataframe
import pandas as pd
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
df4 = pd.DataFrame(data4)

In [ ]:
# combine the dataframes
df = pd.concat([df1,df2,df3,df4], ignore_index= False)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 249
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                1000 non-null   object
 1   symbol                            1000 non-null   object
 2   name                              1000 non-null   object
 3   image                             1000 non-null   object
 4   current_price                     1000 non-null   float64
 5   market_cap                        1000 non-null   int64
 6   market_cap_rank                   1000 non-null   int64
 7   fully_diluted_valuation           998 non-null    float64
 8   total_volume                      985 non-null    float64
 9   high_24h                          988 non-null    float64
 10  low_24h                           988 non-null    float64
 11  price_change_24h                  988 non-null    float64
 12  price_change_percentage_24h       988 non-null    float64
 13  market_cap_change_24h             986 non-null    float64
 14  market_cap_change_percentage_24h  986 non-null    float64
 15  circulating_supply                1000 non-null   float64
 16  total_supply                      998 non-null    float64
 17  max_supply                        643 non-null    float64
 18  ath                               1000 non-null   float64
 19  ath_change_percentage             1000 non-null   float64
 20  ath_date                          1000 non-null   object
 21  atl                               1000 non-null   float64
 22  atl_change_percentage             1000 non-null   float64
 23  atl_date                          1000 non-null   object
 24  roi                               88 non-null     object
 25  last_updated                      1000 non-null   object
dtypes: float64(16), int64(2), object(8)
memory usage: 210.9+ KB

In [ ]:
import pandas as pd

# 1. Define the list of columns you want
selected_columns = [
    'id', 'symbol', 'name', 'current_price', 'market_cap',
    'market_cap_rank', 'total_volume', 'circulating_supply',
    'total_supply', 'ath', 'atl', 'last_updated'
]

# 2. Filter the DataFrame
filtered_df = df[selected_columns].copy()

# 3. Convert 'last_updated' to just a Date (removing the time)
filtered_df['last_updated'] = pd.to_datetime(filtered_df['last_updated']).dt.date

# View the result
filtered_df

NameError: name 'df' is not defined

In [ ]:
filtered_df.reset_index().to_csv("Cryptocurrency_Filtered.csv",index=False)

# TOP 3 COINS

"bitcoin","ethereum","tether",

In [ ]:
coin_id = "tether" # change it to ethereum,tether accordingly
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
response = requests.get(url)

tether_data = response.json()

In [ ]:
import pandas as pd
tether_df = pd.DataFrame(tether_data)
tether_df

,prices,market_caps,total_volumes
0,"[1741046400000, 574.3332822956445]","[1741046400000, 84131864548.38559]","[1741046400000, 1502671244.0216174]"
1,"[1741132800000, 583.1532087181396]","[1741132800000, 85076550479.04813]","[1741132800000, 1296685222.7007513]"
2,"[1741219200000, 597.848549405523]","[1741219200000, 87308885656.99092]","[1741219200000, 565172537.3879949]"
3,"[1741305600000, 595.9383138170398]","[1741305600000, 86832048702.56416]","[1741305600000, 840033139.4891893]"
4,"[1741392000000, 594.5528006856207]","[1741392000000, 86659310630.1766]","[1741392000000, 1083021829.4095507]"
...,...,...,...
361,"[1772236800000, 613.9686612193877]","[1772236800000, 83730647972.7378]","[1772236800000, 1166358389.1914895]"
362,"[1772323200000, 617.5322050027751]","[1772323200000, 84176037496.01993]","[1772323200000, 1209591660.7041028]"
363,"[1772409600000, 616.8269097979393]","[1772409600000, 84170308777.82892]","[1772409600000, 1186979235.562409]"
364,"[1772496000000, 637.4936332653224]","[1772496000000, 86949777841.90884]","[1772496000000, 1468743400.2500687]"
365,"[1772537940000, 626.4296605681601]","[1772537940000, 85319098721.20383]","[1772537940000, 1641280532.2325547]"

In [ ]:
tether_df['timestamp'] = tether_df['prices'].apply(lambda x: x[0])
tether_df['timestamp'] = pd.to_datetime(tether_df['timestamp'], unit='ms')

tether_df['prices'] = tether_df['prices'].apply(lambda x: x[1])
tether_df['market_caps'] = tether_df['market_caps'].apply(lambda x: x[1])
tether_df['total_volumes'] = tether_df['total_volumes'].apply(lambda x: x[1])

tether_df = tether_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]

tether_df

              timestamp    prices   market_caps  total_volumes
0   2025-03-04 00:00:00  0.999253  1.423283e+11   1.155309e+11
1   2025-03-05 00:00:00  0.999775  1.424759e+11   5.770701e+10
2   2025-03-06 00:00:00  0.999975  1.424923e+11   7.547209e+10
3   2025-03-07 00:00:00  1.000019  1.427211e+11   7.014513e+10
4   2025-03-08 00:00:00  0.999571  1.427385e+11   8.449896e+10
..                  ...       ...           ...            ...
361 2026-02-28 00:00:00  1.000038  1.835488e+11   7.126240e+10
362 2026-03-01 00:00:00  1.000355  1.836477e+11   7.613496e+10
363 2026-03-02 00:00:00  1.000049  1.836459e+11   7.410037e+10
364 2026-03-03 00:00:00  1.000036  1.836424e+11   9.789655e+10
365 2026-03-03 08:58:19  0.999864  1.835974e+11   9.848728e+10

[366 rows x 4 columns]

In [ ]:
ethereum_df['timestamp'] = ethereum_df['prices'].apply(lambda x: x[0])
ethereum_df['timestamp'] = pd.to_datetime(ethereum_df['timestamp'], unit='ms')

ethereum_df['prices'] = ethereum_df['prices'].apply(lambda x: x[1])
ethereum_df['market_caps'] = ethereum_df['market_caps'].apply(lambda x: x[1])
ethereum_df['total_volumes'] = ethereum_df['total_volumes'].apply(lambda x: x[1])

ethereum_df = ethereum_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]

ethereum_df

In [ ]:
bitcoin_df['timestamp'] = bitcoin_df['prices'].apply(lambda x: x[0])
bitcoin_df['timestamp'] = pd.to_datetime(bitcoin_df['timestamp'], unit='ms')

bitcoin_df['prices'] = bitcoin_df['prices'].apply(lambda x: x[1])
bitcoin_df['market_caps'] = bitcoin_df['market_caps'].apply(lambda x: x[1])
bitcoin_df['total_volumes'] = bitcoin_df['total_volumes'].apply(lambda x: x[1])

bitcoin_df = bitcoin_df[['timestamp', 'prices', 'market_caps', 'total_volumes']]

bitcoin_df

In [ ]:
df = pd.concat([bitcoin_df,ethereum_df,tether_df], ignore_index= False)
df['timestamp'] = df['timestamp'].dt.date

In [ ]:
df = df.drop(columns=['total_volumes','market_caps'])
df.to_csv("")

# OIL PRICES

In [ ]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
filtered_df = oil_df[oil_df['Date'].between('2020-01-01', '2026-02-28')]
filtered_df

             Date  Price
8569   2020-01-02  61.17
8570   2020-01-03  63.00
8571   2020-01-06  63.27
8572   2020-01-07  62.70
8573   2020-01-08  59.65
...           ...    ...
10099  2026-02-17  62.53
10100  2026-02-18  65.33
10101  2026-02-19  66.66
10102  2026-02-20  66.69
10103  2026-02-23  66.36

[1535 rows x 2 columns]

In [ ]:
filtered_df.reset_index().to_csv("oil_prices.csv", index=False)

In [ ]:
oil_df = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/oil_prices.csv")
oil_df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1530  2026-02-17  62.53
1531  2026-02-18  65.33
1532  2026-02-19  66.66
1533  2026-02-20  66.69
1534  2026-02-23  66.36

[1535 rows x 2 columns]

In [ ]:
teth = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Bitcoin_Historical_Prices - Bitcoin_Historical_Prices.csv")

In [ ]:
import pandas as pd

# 1. Convert the column to actual datetime objects
teth['timestamp'] = pd.to_datetime(teth['timestamp'])

# 2. Extract just the date (this removes the 0:00:00)
teth['date'] = teth['timestamp'].dt.date

teth.to_csv("Bitcoin.csv",index=False)

# Stock Prices (Yahoo Finance API)

In [ ]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df

/tmp/ipykernel_1138/2667130780.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^IXIC                                            \
Price               Open          High           Low         Close
Date
2020-01-01           NaN           NaN           NaN           NaN
2020-01-02   9039.459961   9093.429688   9010.889648   9092.190430
2020-01-03   8976.429688   9065.759766   8976.429688   9020.769531
2020-01-06   8943.500000   9072.410156   8943.500000   9071.469727
2020-01-07   9076.639648   9091.929688   9042.549805   9068.580078
...                  ...           ...           ...           ...
2026-02-16           NaN           NaN           NaN           NaN
2026-02-17  22394.759766  22690.830078  22256.759766  22578.380859
2026-02-18  22629.849609  22895.960938  22597.769531  22753.630859
2026-02-19  22639.880859  22768.830078  22583.609375  22682.730469
2026-02-20  22542.279297  22948.869141  22539.050781  22886.070312

Ticker                           ^NSEI                              \
Price             Volume          Open          High           Low
Date
2020-01-01           NaN  12202.150391  12222.200195  12165.299805
2020-01-02  2.862700e+09  12198.549805  12289.900391  12195.250000
2020-01-03  2.586520e+09  12261.099609  12265.599609  12191.349609
2020-01-06  2.810450e+09  12170.599609  12179.099609  11974.200195
2020-01-07  2.381740e+09  12079.099609  12152.150391  12005.349609
...                  ...           ...           ...           ...
2026-02-16           NaN  25423.599609  25697.000000  25372.699219
2026-02-17  7.654300e+09  25637.949219  25764.400391  25570.300781
2026-02-18  7.705590e+09  25752.650391  25828.050781  25645.150391
2026-02-19  6.984780e+09  25873.349609  25885.300781  25388.750000
2026-02-20  8.063070e+09  25406.550781  25663.550781  25379.750000

Ticker                                    ^GSPC                            \
Price              Close    Volume         Open         High          Low
Date
2020-01-01  12182.500000  304100.0          NaN          NaN          NaN
2020-01-02  12282.200195  407700.0  3244.669922  3258.139893  3235.530029
2020-01-03  12226.650391  428800.0  3226.360107  3246.149902  3222.340088
2020-01-06  11993.049805  396500.0  3217.550049  3246.840088  3214.639893
2020-01-07  12052.950195  447800.0  3241.860107  3244.909912  3232.429932
...                  ...       ...          ...          ...          ...
2026-02-16  25682.750000  275800.0          NaN          NaN          NaN
2026-02-17  25725.400391  344100.0  6819.859863  6866.990234  6775.500000
2026-02-18  25819.349609  310200.0  6855.479980  6909.120117  6849.660156
2026-02-19  25454.349609  298200.0  6861.339844  6879.120117  6833.060059
2026-02-20  25571.250000  296600.0  6843.259766  6915.859863  6836.330078

Ticker
Price             Close        Volume
Date
2020-01-01          NaN           NaN
2020-01-02  3257.850098  3.459930e+09
2020-01-03  3234.850098  3.484700e+09
2020-01-06  3246.280029  3.702460e+09
2020-01-07  3237.179932  3.435910e+09
...                 ...           ...
2026-02-16          NaN           NaN
2026-02-17  6843.220215  5.418480e+09
2026-02-18  6881.310059  5.098160e+09
2026-02-19  6861.890137  5.151690e+09
2026-02-20  6909.509766  5.432480e+09

[1593 rows x 15 columns]

In [ ]:
stocks_df.to_csv("stodf.csv", index=False)

In [ ]:
stocks_1 = stocks_df['^NSEI'].reset_index()
stocks_1["Ticker"] = "^NSEI"
stocks_1

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI
...,...,...,...,...,...,...,...
1588,2026-02-16,25423.599609,25697.000000,25372.699219,25682.750000,275800.0,^NSEI
1589,2026-02-17,25637.949219,25764.400391,25570.300781,25725.400391,344100.0,^NSEI
1590,2026-02-18,25752.650391,25828.050781,25645.150391,25819.349609,310200.0,^NSEI
1591,2026-02-19,25873.349609,25885.300781,25388.750000,25454.349609,298200.0,^NSEI
1592,2026-02-20,25406.550781,25663.550781,25379.750000,25571.250000,296600.0,^NSEI

In [ ]:
stocks_2 = stocks_df['^IXIC'].reset_index()
stocks_2["Ticker"] = "^IXIC"
stocks_2

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^IXIC
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,^IXIC
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,^IXIC
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,^IXIC
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,^IXIC
...,...,...,...,...,...,...,...
1588,2026-02-16,NaN,NaN,NaN,NaN,NaN,^IXIC
1589,2026-02-17,22394.759766,22690.830078,22256.759766,22578.380859,7.654300e+09,^IXIC
1590,2026-02-18,22629.849609,22895.960938,22597.769531,22753.630859,7.705590e+09,^IXIC
1591,2026-02-19,22639.880859,22768.830078,22583.609375,22682.730469,6.984780e+09,^IXIC
1592,2026-02-20,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09,^IXIC

In [ ]:
stocks_3 = stocks_df['^GSPC'].reset_index()
stocks_3["Ticker"] = "^GSPC"
stocks_3

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
...,...,...,...,...,...,...,...
1588,2026-02-16,NaN,NaN,NaN,NaN,NaN,^GSPC
1589,2026-02-17,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09,^GSPC
1590,2026-02-18,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09,^GSPC
1591,2026-02-19,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09,^GSPC
1592,2026-02-20,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09,^GSPC

In [ ]:
stocks_df = pd.concat([stocks_1,stocks_2,stocks_3],ignore_index=True)
stocks_df

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05,^NSEI
...,...,...,...,...,...,...,...
4774,2026-02-16,NaN,NaN,NaN,NaN,NaN,^GSPC
4775,2026-02-17,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09,^GSPC
4776,2026-02-18,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09,^GSPC
4777,2026-02-19,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09,^GSPC
4778,2026-02-20,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09,^GSPC

In [ ]:
stocks_df.to_csv("Stocks_con.csv",index=True)

In [2]:
import pandas as pd
crpyto_curr = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Cryptocurrencies.csv")
crpyto_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Crypto_prices.csv")
oil_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Oil_prices.csv")
stocks_price = pd.read_csv("/content/drive/MyDrive/datascience/Mini Projects/DS_Cross-Market Analysis/Stocks_prices.csv")

In [3]:
import sqlite3
import pandas as pd

# Connect to one database file (usually better than 4 separate files)
conn = sqlite3.connect("Cross_Market_Analysis")
cursor = conn.cursor()

# Define specific schemas for your 4 tables
tables = {
    "Cryptocurrencies": "id VARCHAR(50) PRIMARY KEY, symbol VARCHAR(10),	name VARCHAR(100),	current_price DECIMAL(18, 6),	market_cap BIGINT,	market_cap_rank INT,	total_volume BIGINT,	circulating_supply DECIMAL(20, 6),	total_supply DECIMAL(20, 6),	ath DECIMAL(18, 6),	atl DECIMAL(18, 6),	date DATE",
    "Crypto_prices": "coin_id	VARCHAR(50), date	DATE, prices_usd DECIMAL(18, 6)",
    "Oil_prices": "Date DATE PRIMARY KEY, Price DECIMAL(18, 6)",
    "Stocks_prices": "Date DATE,	Open DECIMAL(18, 6),	High DECIMAL(18, 6) , Low DECIMAL(18, 6),	Close DECIMAL(18, 6),	Volume DECIMAL(18, 6),	Ticker DECIMAL(18, 6)"
}

for table_name, schema in tables.items():
    cursor.execute(f"CREATE TABLE IF NOT EXISTS {table_name} ({schema})")

In [4]:
# List of pairs
df_list = [
    (crpyto_curr, "Cryptocurrencies"),
    (crpyto_price, "Crypto_prices"),
    (oil_price, "Oil_prices"),
    (stocks_price, "Stocks_prices")
]

for df, table_name in df_list:
    # FIX: Wrap column names in [] to handle colons or spaces
    cols = ", ".join([f"[{col}]" for col in df.columns])
    placeholders = ", ".join(["?"] * len(df.columns))

    # FIX: Wrap table name in [] just in case
    sql = f"INSERT OR REPLACE INTO [{table_name}] ({cols}) VALUES ({placeholders})"

    for _, row in df.iterrows():
        # Ensure values are passed as a clean tuple
        cursor.execute(sql, tuple(row))

conn.commit()
print("Data inserted successfully without token errors.")

Data inserted successfully without token errors.

In [5]:
!pip install datetime timedelta

Collecting datetime
  Downloading datetime-6.0-py3-none-any.whl.metadata (34 kB)
Collecting timedelta
  Downloading timedelta-2020.12.3.tar.gz (1.6 kB)
  Preparing metadata (setup.py) ... done
Collecting zope.interface (from datetime)
  Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from datetime) (2025.2)
Downloading datetime-6.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 4.3 MB/s eta 0:00:00
Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.9/264.9 kB 10.7 MB/s eta 0:00:00
Building wheels for collected packages: timedelta
  Building wheel for timedelta (setup.py) ... done
  Created wheel for timedelta: filename=timedelta-2020.12.3-py3-none-any.whl size=1555 sha256=8fb60e05aa825d997055f83f6e0d4be0e5baaf087926acb438adb5a22ffc033b
  Stored in directory: /root/.cache/pip/wheels/8d/fb/00/1ed61af72177d4c71909dc4ad90d4ce863e0aaed78e31206e0
Successfully built timedelta
Installing collected packages: timedelta, zope.interface, datetime
Successfully installed datetime-6.0 timedelta-2020.12.3 zope.interface-8.2

In [6]:
!pip install streamlit streamlit_option_menu

Collecting streamlit
  Downloading streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Collecting streamlit_option_menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.55.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 56.3 MB/s eta 0:00:00
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 39.3 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 95.4 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit, streamlit_option_menu
Successfully installed pydeck-0.9.1 streamlit-1.55.0 streamlit_option_menu-0.4.0

In [7]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-03-11 10:20:29--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-11 10:20:29--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-11T11%3A01%3A22Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-11T10%3A00%3A37Z&ske=2026-03-11T11%3A01%3A22Z&sks=b&skv=2018-11-09&sig=M0f9E43oK%2Buk83yAAUOC14J8V9qO8dGDZI5X4KwimU0%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzIyNjIyOSwibmJmIjoxNzczMjI0NDI5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.cDOGwLYXb2Oxy8ApznHY2tb-7gwgTGdtoAtyLKNYW2k&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-11 10:20:29--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-11T11%3A01%3A22Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-11T10%3A00%3A37Z&ske=2026-03-11T11%3A01%3A22Z&sks=b&skv=2018-11-09&sig=M0f9E43oK%2Buk83yAAUOC14J8V9qO8dGDZI5X4KwimU0%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzIyNjIyOSwibmJmIjoxNzczMjI0NDI5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.cDOGwLYXb2Oxy8ApznHY2tb-7gwgTGdtoAtyLKNYW2k&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.83M   232MB/s    in 0.2s

2026-03-11 10:20:30 (232 MB/s) - ‘cloudflared-linux-amd64’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

In [11]:
%%writefile cross.py

import streamlit as st
from streamlit_option_menu import option_menu
import sqlite3
import pandas as pd
import time
from datetime import date

# ---------------------- CONFIG ----------------------
st.set_page_config(
    page_title="Cross-Market Analysis",
    page_icon="📊",
    layout="wide"
)

# ---------------------- DB CONNECTION ----------------------
conn = sqlite3.connect("Cross_Market_Analysis")
cursor = conn.cursor()

# ---------------------- SIDEBAR ----------------------
with st.sidebar:
    page = option_menu(
        menu_title="🌐 Navigation",
        options=["📊 Market Overview", "🔎 SQL Query Runner", "🏆 Top 3 Crypto Analysis"],
        icons=[" ", " ", " "],
        menu_icon =" ",
        default_index=0,
    )

# ======================================================
# PAGE 1 : FILTERS & DATA EXPLORATION
# ======================================================
if page == "📊 Market Overview":

    st.title("📊 Cross-Market Overview")
    st.caption("Crypto • Oil • Stock Market | SQL-powered analytics")

    # ---------- DATE FILTER ----------
    col1, col2 = st.columns(2)

    min_date = date(2020, 1, 1)
    max_date = date(2026, 3, 3)

    with col1:
      start_date = st.date_input("Start Date",value=min_date,min_value=min_date,max_value=max_date,key="c1")
    with col2:
      end_date = st.date_input("End Date", value=max_date,min_value=min_date,max_value=max_date,key="c2")

    # ---------- KPI CARDS ----------
    k1, k2, k3, k4 = st.columns(4)

    btc_avg = pd.read_sql(f"""
        SELECT AVG(prices_usd)
        FROM Crypto_prices
        WHERE coin_id='bitcoin' and
        date BETWEEN ? AND ?
        """, conn,params=(start_date, end_date)).iloc[0,0]

    oil_avg = pd.read_sql(f"""
        SELECT AVG(price)
        FROM Oil_prices
        WHERE date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    sp500_avg = pd.read_sql(f"""
        SELECT AVG(close)
        FROM Stocks_prices
        WHERE ticker='^GSPC'
        AND date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    nifty_avg = pd.read_sql(f"""
        SELECT AVG(close)
        FROM Stocks_prices
        WHERE ticker='^NSEI'
        AND date BETWEEN '{start_date}' AND '{end_date}'
    """, conn).iloc[0, 0]

    k1.metric("₿ Bitcoin Avg ($)", f"{btc_avg:,.2f}")
    k2.metric("🛢️ Oil Avg ($)", f"{oil_avg:,.2f}" if oil_avg else "N/A")
    k3.metric("📈 S&P 500 Avg", f"{sp500_avg:,.2f}" if sp500_avg else "N/A")
    k4.metric("🇮🇳 NIFTY Avg", f"{nifty_avg:,.2f}" if nifty_avg else "N/A")

    st.divider()

    # ---------- FILTERED DATA TABLE ----------
    st.subheader("📈 Market Pulse")

    snapshot_df = pd.read_sql(f"""
        SELECT cp.date,
               cp.prices_usd AS bitcoin_price,
               op.price AS oil_price,
               sp1.close AS sp500,
               sp2.close AS nifty
        FROM Crypto_prices cp
        JOIN Oil_prices op ON cp.date = op.date
        JOIN Stocks_prices sp1 ON cp.date = sp1.date AND sp1.ticker='^GSPC'
        JOIN Stocks_prices sp2 ON cp.date = sp2.date AND sp2.ticker='^NSEI'
        WHERE cp.coin_id='bitcoin'
        AND cp.date BETWEEN '{start_date}' AND '{end_date}'
        ORDER BY cp.date DESC
    """, conn)

    st.dataframe(snapshot_df, use_container_width=True)

# ======================================================
# PAGE 2 : SQL QUERY RUNNER
# ======================================================
elif page == "🔎 SQL Query Runner":

    st.title("🔎 SQL Query Runner")

    st.caption("Predefined analytical SQL queries")

    queries = {

# ===============================
# 1️⃣ CRYPTOCURRENCIES (5)
# ===============================

"Top 3 Cryptocurrencies by Market Cap": """
    SELECT name, market_cap
    FROM Cryptocurrencies
    ORDER BY market_cap DESC
    LIMIT 3;
""",

"Coins with Circulating Supply > 90%": """
    SELECT name , circulating_supply , total_supply
    FROM Cryptocurrencies
    WHERE circulating_supply / total_supply > 0.9;
""",

"Coins Near All-Time High (Within 10%)": """
    SELECT name, current_price, ath
    FROM Cryptocurrencies
    WHERE current_price >= ath * 0.9;
""",

"Average Market Cap Rank (Volume > $1B)": """
    SELECT name, date , AVG(market_cap_rank)  AS avg_rank
    FROM Cryptocurrencies
    WHERE total_volume > 1000000000;
""",

"Most Recently Updated Coin": """
    SELECT name, date
    FROM Cryptocurrencies
    ORDER BY date DESC
    LIMIT 1;
""",

# ===============================
# 2️⃣ CRYPTO PRICES (5)
# ===============================

"Highest Bitcoin Price (Last 1 year)": """
    SELECT MAX(prices_usd), date
    FROM Crypto_prices
    WHERE coin_id = 'bitcoin';
""",

"Average Ethereum Price (Past 1 Year)": """
    SELECT coin_id, AVG(prices_usd), date
    FROM Crypto_prices
    WHERE coin_id = 'ethereum';
""",

"Bitcoin Prices – January 2026": """
    SELECT coin_id, date, prices_usd
    FROM Crypto_prices
    WHERE coin_id = 'bitcoin'
    AND date BETWEEN '2026-01-01' AND '2026-01-31';
""",

"Coin with Highest Average Price": """
    SELECT coin_id, AVG(prices_usd) AS avg_price
    FROM Crypto_prices
    GROUP BY coin_id
    ORDER BY avg_price DESC
    LIMIT 1;
""",

"Bitcoin % Change (Mar 2025 – Mar 2026)": """
    SELECT coin_id,
    ((MAX(prices_usd) - MIN(prices_usd)) / MIN(prices_usd)) * 100 AS pct_change
    FROM Crypto_prices
    WHERE coin_id='bitcoin'
    AND date BETWEEN '2025-03-03' AND '2026-03-03';
""",

# ===============================
# 3️⃣ OIL PRICES (5)
# ===============================

"Highest Oil Price (Last 5 Years)": """
    SELECT MAX(price) AS Price_USD, date
    FROM Oil_prices
    WHERE date >= DATE('2026-03-03', '-5 years');
""",

"Average Oil Price Per Year": """
    SELECT strftime('%Y', date) AS year, AVG(price) AS Avg_price_USD
    FROM Oil_prices
    GROUP BY year;
""",

"Oil Prices During COVID Crash": """
    SELECT *
    FROM Oil_prices
    WHERE date BETWEEN '2020-03-01' AND '2020-04-30';
""",

"Lowest Oil Price (Last 5 Years)": """
    SELECT MIN(price) , date
    FROM Oil_prices
    WHERE date >= DATE('2026-03-03', '-5 years');
""",

"Yearly Oil Price Volatility": """
    SELECT strftime('%Y', date) AS Year,
           MAX(price) - MIN(price) AS Volatility
    FROM Oil_prices
    GROUP BY Year;
""",

# ===============================
# 4️⃣ STOCK PRICES (5)
# ===============================

"All Prices for NSEI S&P 500": """
    SELECT *
    FROM Stocks_prices
    WHERE ticker = '^NSEI';
""",

"Highest NASDAQ (^IXIC) Closing Price": """
    SELECT MAX(close) , ticker
    FROM Stocks_prices
    WHERE ticker='^IXIC';
""",

"Top 5 Volatile S&P 500 Days": """
    SELECT date, high , low, (high - low) AS volatility
    FROM Stocks_prices
    WHERE ticker='^GSPC'
    ORDER BY volatility DESC
    LIMIT 5;
""",

"Monthly Average Closing Price (All Tickers)": """
    SELECT ticker,
           strftime('%Y-%m', date) AS Month,
           AVG(close) AS Avg_close
    FROM Stocks_prices
    GROUP BY ticker, month;
""",

"Average NSEI Volume (2024)": """
    SELECT ticker, AVG(volume)
    FROM Stocks_prices
    WHERE ticker='^NSEI'
    AND date BETWEEN '2024-01-01' AND '2024-12-31';
""",

# ===============================
# 5️⃣ CROSS-MARKET JOINS (10)
# ===============================

"Bitcoin vs Oil Average Price (2025)": """
    SELECT AVG(cp.prices_usd) AS Btc_avg,
           AVG(op.price) AS Oil_avg
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    WHERE cp.coin_id='bitcoin'
    AND cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Bitcoin vs S&P 500 (Daily)": """
    SELECT cp.date, cp.prices_usd AS Btc_price, sp.close AS sp500
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='bitcoin'
    AND sp.ticker='^GSPC';
""",

"Ethereum vs NASDAQ (2025)": """
    SELECT cp.date, cp.prices_usd, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='ethereum'
    AND sp.ticker='^IXIC'
    AND cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Oil Spike Days vs Bitcoin Price": """
    SELECT op.date, op.price AS Oil_price, cp.prices_usd AS Btc_price
    FROM Oil_prices op
    JOIN Crypto_prices cp ON op.date = cp.date
    WHERE cp.coin_id='bitcoin'
    AND op.price > (SELECT AVG(price) FROM Oil_prices)
    ORDER BY op.date DESC;
""",

"Top 3 Coins vs NIFTY": """
    SELECT cp.date, cp.coin_id, cp.prices_usd, sp.close AS NIFTY
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE sp.ticker='^NSEI';
""",

"S&P 500 vs Oil Prices on same date": """
    SELECT sp.date, sp.close, op.price AS Oil_Price
    FROM Stocks_prices sp
    JOIN Oil_prices op ON sp.date = op.date
    WHERE sp.ticker='^GSPC';
""",

"Bitcoin vs Oil Correlation Dataset": """
    SELECT cp.date, cp.prices_usd AS Btc_price, op.price AS Oil_Price
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    WHERE cp.coin_id='bitcoin'
    ORDER BY cp.date DESC;
""",

"NASDAQ vs Ethereum Trend": """
    SELECT cp.date, cp.prices_usd, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='ethereum'
    AND sp.ticker='^IXIC'
    ORDER BY cp.date DESC;
""",

"Top 3 Cryptos vs Stock Indices (2025)": """
    SELECT cp.date, cp.coin_id, cp.prices_usd, sp.ticker, sp.close
    FROM Crypto_prices cp
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.date BETWEEN '2025-01-01' AND '2025-12-31';
""",

"Bitcoin + Oil + S&P 500 Daily Comparison": """
    SELECT cp.date,
           cp.prices_usd AS Btc_price,
           op.price AS Oil_price,
           sp.close AS sp500
    FROM Crypto_prices cp
    JOIN Oil_prices op ON cp.date = op.date
    JOIN Stocks_prices sp ON cp.date = sp.date
    WHERE cp.coin_id='bitcoin'
    AND sp.ticker='^GSPC';
"""
}


    selected_query = st.selectbox("📌 Select a Query", list(queries.keys()))

    if st.button("▶ Run Query"):
        result = pd.read_sql(queries[selected_query], conn)
        with st.spinner("⚡ Running Instant Analysis..."):
          time.sleep(2)
          st.success("Query executed successfully")
        st.dataframe(result, use_container_width=True)

    st.caption("🔗 Direct-to-source: Executing against the SQL database.")

# ======================================================
# PAGE 3 : TOP 3 CRYPTO ANALYSIS (as per document)
# ======================================================
elif page == "🏆 Top 3 Crypto Analysis":

    st.title("🏆 Top 3 Crypto Analysis")
    st.caption("Daily price analysis for top cryptocurrencies")

    coins = pd.read_sql("""
        SELECT DISTINCT coin_id
        FROM Crypto_prices
    """, conn)['coin_id'].tolist()

    selected_coin = st.selectbox("Select a Cryptocurrency", coins)

    col1, col2 = st.columns(2)

    min_date = date(2025, 3, 3)
    max_date = date(2026, 3, 3)

    with col1:
      start_date = st.date_input("Start Date",value=min_date,min_value=min_date,max_value=max_date,key="c1")
    with col2:
      end_date = st.date_input("End Date", value=max_date,min_value=min_date,max_value=max_date,key="c2")

    price_df = pd.read_sql(f"""
        SELECT date, prices_usd
        FROM Crypto_prices
        WHERE coin_id='{selected_coin}'
        AND date BETWEEN '{start_date}' AND '{end_date}'
        ORDER BY date
    """, conn)

    podium_map = {
    "bitcoin": "🥇 1st Place: BITCOIN",
    "ethereum": "🥈 2nd Place: ETHEREUM",
    "tether": "🥉 3rd Place: TETHER"}

    display_title = podium_map[selected_coin.lower()]
    st.subheader(display_title)
    st.line_chart(price_df.set_index('date'))

    st.dataframe(price_df, use_container_width=True)

Overwriting cross.py

In [9]:
!streamlit run /content/cross.py &>/content/logs.txt &

In [10]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://housewives-remote-sheriff-broadcasting.trycloudflare.com